import type { AQIModelOutput } from '../types/aqi';

export const SAMPLE_AQI: AQIModelOutput = {
  datetime: '2025-10-05T12:00:00Z',
  AQI_total_pred: 142,
  AQI_level_text: 'Unhealthy for Sensitive Groups',
  health_alert: "Air quality is poor. People with asthma or heart conditions should avoid prolonged outdoor activity.",
  main_pollutants: ['PM2.5', 'NO2', 'O3'],
  pollutant_percentages: {
    'PM2.5': 48.3,
    NO2: 27.6,
    O3: 24.1,
  },
  weather_summary: 'Moderate winds from the southwest with light clouds.',
  temperature_pred_C: 31.2,
  humidity_pred_percent: 68.4,
  wind_speed_pred_ms: 3.5,
  pressure_pred_hPa: 1007.8,
  forecast_next_24h: [
    {
      datetime: '2025-10-05T13:00:00Z',
      temperature_pred_C: 31.5,
      humidity_pred_percent: 67.5,
      wind_speed_pred_ms: 3.6,
      pressure_pred_hPa: 1007.9,
      AQI_total_pred: 135,
      AQI_level_text: 'Moderate',
      main_pollutants: ['PM2.5', 'O3'],
      AQI_color_code: '#FFFF00',
    },
    {
      datetime: '2025-10-05T14:00:00Z',
      temperature_pred_C: 32.1,
      humidity_pred_percent: 64.8,
      wind_speed_pred_ms: 4.0,
      pressure_pred_hPa: 1007.6,
      AQI_total_pred: 145,
      AQI_level_text: 'Unhealthy for Sensitive Groups',
      main_pollutants: ['PM2.5', 'NO2'],
      AQI_color_code: '#FF7E00',
    },
    {
      datetime: '2025-10-05T15:00:00Z',
      temperature_pred_C: 33.0,
      humidity_pred_percent: 63.1,
      wind_speed_pred_ms: 4.3,
      pressure_pred_hPa: 1007.4,
      AQI_total_pred: 155,
      AQI_level_text: 'Unhealthy',
      main_pollutants: ['PM2.5'],
      AQI_color_code: '#FF0000',
    },
  ],
  population_risk_groups: ['Children', 'Elderly', 'Asthmatics', 'Cardiac patients'],
  recommended_actions: ['Avoid intense outdoor activities.', 'Keep windows closed.', 'Use an air purifier if possible.'],
  disease_specific_risk: 'Asthma: High; Hypertension: Moderate; BPCO: High; Pregnancy: Low',
  AQI_color_code: '#FF7E00',
  visual_summary_chart: undefined,
};
